# Generated by Django 4.1.2 on 2023-12-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlaut_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitkarang',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
